config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    
	root 'posts#index'

	resources :comments

	resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@comments = Comment.all.order("created_at DESC")
		@posts = Post.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@comment = current_user.comments.build
	end

	def create
		@comment = current_user.comments.build(comment_params)

		if @comment.save
			redirect_to comments_path
		else
			render comments_path
		end
	end

	def edit
	end

	def update
		if @comment.update
			redirect_to @comment
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to comments_path
	end

	private

	def find_post
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show]
	before_action :authenticate_user!
	def index
		@post = Post.new()
	end

	def new 
		@post = Post.new()
	end

	def show
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to new_comment_path
		else
			render 'new'
		end
	end


	private 

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:skin, 
									:head,  
									:hair, 
									:hairbacking,
									:eye, 
									:eyebrow, 
									:nose, 
									:mouth, 
									:facehair, 
									:spectacles)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for @comment do |f| %>
  <%= f.input :content, placeholder: 'Tell us what you thought', label: false, required: true%>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<%= stylesheet_link_tag 'comments'%>
<%= link_to "Home", root_path, :class => 'home' %>

<div class="avatar-scroll">
<% @posts.each do |post| %>
	<div class="section" id="avatar-view" >
		<div class="avatar">
			<img id="body" src="/images/ears0.png">
			<img class="clothing" id="worn-skin" src="/<%= post.skin %>"></img>
			<img class="clothing" id="worn-head" src="/<%= post.head %>"></img>
			<img class="clothing" id="worn-top" src="/images/items/tops/top0.png"></img>
			<img class="clothing" id="worn-bottom" src="/images/items/bottoms/bottom0.png"></img>
			<img class="clothing" id="worn-hair" src="/<%= post.hair %>"></img>
			<img class="clothing" id="hair-backing" src="/<%= post.hairbacking %>"></img>
			<img class="clothing" id="worn-shoe" src="/images/items/shoes/shoe0.png"></img>
			<img class="clothing" id="worn-eye" src="/<%= post.eye %>"></img>
			<img class="clothing" id="worn-eyebrow" src="/<%= post.eyebrow %>"></img>
			<img class="clothing" id="worn-spectacle" src="/<%= post.spectacles %>"></img>
			<img class="clothing" id="worn-nose" src="/<%= post.nose %>"></img>
			<img class="clothing" id="worn-mouth" src="/<%= post.mouth %>"></img>
			<img class="clothing" id="worn-facehair" src="/<%= post.facehair %>"></img>
		</div>
	</div>
<% end %>
</div>
<h1 class="comments-header">Comments</h1>

<% @comments.each do |comment| %>
<div class="comment">
    <p class="comment-content"><%= comment.content %></p>
	<p class="comment-stamp"><%= (comment.created_at).strftime("%I:%M:%S %p, %d %b %Y, %Z") %> by <%= comment.user.email%></p>
	<br>
</div>



<% end %>


<script type="text/javascript">
// hide broken (missing) images. (if an avatar has no glasses, beard, or hair-backing)
	document.addEventListener("DOMContentLoaded", function(event) {
	Array.from(document.querySelectorAll('img')).forEach(function(img){
  		img.onerror = function(){this.style.display='none';};
   })
});
</script>

app/views/comments/new.html.erb
<%= stylesheet_link_tag 'comments'%>
<h2 class="comments-header">New Comment:</h2>

<%= render 'form' %>

app/views/comments/show.html.erb
<p><%= @comment.content %></p>
<%= link_to "Home", root_path %>
<%= link_to "Comments", comments_path %>
<%= link_to "Delete", comment_path(@comment), method: :delete, data: {confirm: "You sure?"}, class: 'label alert' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <script src="/fastclick.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <title>Lawnmower Man</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>


    <link rel="apple-touch-icon" href="touch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="167x167" href="/images/touch-icon-ipad-retina.png">
  </head>

  <body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<head>
	<link rel="stylesheet" type="text/css" href="noUiSlider/nouislider.css">
	<script src="noUiSlider/nouislider.js"></script>
	<%= stylesheet_link_tag 'posts'%>
</head>
<body>
<%= simple_form_for @post do |f| %>
  <%= f.input :skin %>
  <%= f.input :head %>
  <%= f.input :hair %>
  <%= f.input :hairbacking %>
  <%= f.input :eye %>
  <%= f.input :eyebrow %>
  <%= f.input :spectacles %>
  <%= f.input :nose %>
  <%= f.input :mouth %>
  <%= f.input :facehair %>
  <div id="next-button"><%= f.submit :a , :as => :hidden,
      :input_html => {
        :id => "submit-button"
      } %></div>
  
<% end %>

<!-- <a href="comments/new"> -->

<!-- </a> -->
<p id="randomizer" class="visible-on-white">randomizer!</p>

<div id="loading-screen">THANK YOU, LOADING NAO</div>

<div id="stats-button" class="visible-on-white"><%= link_to 'comments', 'comments'%></div>

<div id="scaler" class="scaler" ><p class="scaler-text">SCALE</p></div>

<div id="color-slider" class="">
	<div class="bw-picker" id="black"></div><div class="bw-picker" id="white"></div><p class="color-slider-text">COLOR</p>
</div>

	<div class="section" id="avatar-view">
	<div class="bg-change"></div>
		<div class="avatar">
			<img id="body" src="images/ears0.png">
			<img data-category="skin" id="worn-skin" class="clothing" src="images/items/skins/skin0.png">
			<img data-category="head" id="worn-head" class="skinnable clothing" src="images/items/heads/head0.png">
			<img data-category="top" id="worn-top" class="clothing" src="images/items/tops/top0.png">
			<img data-category="bottom" id="worn-bottom" class="clothing" src="images/items/bottoms/bottom0.png">
			<img data-category="hair" id="worn-hair" class="clothing" src="images/items/hairs/hair0.png">
			<img id="hair-backing" class="clothing" >
			<img data-category="shoe" id="worn-shoe" class="clothing" src="images/items/shoes/shoe0.png">
			<img data-category="eye" id="worn-eye" class="clothing" src="images/items/eyes/eye0.png">
			<img data-category="eyebrow" id="worn-eyebrow" class="clothing" src="images/items/eyebrows/eyebrow0.png">
			<img data-category="nose" id="worn-nose" class="clothing" src="images/items/noses/nose0.png">
			<img data-category="mouth" id="worn-mouth" class="clothing" src="images/items/mouths/mouth0.png">
			<img data-category="spectacle" id="worn-spectacle" class="clothing" >
			<img data-category="facehair" id="worn-facehair" class="clothing" >
		</div>
	</div>
	
	<div id="selectors">
		<div class="section" id="category-view">
			<ul>
				<div><li data-category="skins" class="category category-selected">SKIN TONE</li></div>
				<div><li data-category="heads" id="headCategory" class="category ">HEAD SHAPE</li></div>
				<div><li data-category="hairs" class="bw-able color-adjustable category">HAIR</li></div>
				<div><li data-category="eyes" class="color-adjustable scalable category">EYES</li></div>
				<div><li data-category="eyebrows" class="scalable category">EYEBROWS</li></div>
				<div><li data-category="noses" class="scalable category nose-button">NOSE</li></div>
				<div><li data-category="mouths" class="scalable category mouth-button">MOUTH</li></div>
				<div><li data-category="spectacles" class="category">GLASSES</li></div>
				<div><li data-category="facehairs" class="category">FACIAL HAIR</li></div>
			</ul>
		</div>
		<div data-category="skins" class="skins-section open-items section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" data-skin="" class=" item-selected skins item item-container"></li>
				<li data-itemnumber="1" data-skin="b" class=" skins item item-container"></li>
				<li data-itemnumber="2" data-skin="c" class=" skins item item-container"></li>
				<li data-itemnumber="3" data-skin="d" class=" skins item item-container"></li>
			</ul>
		</div> 
		<div data-category="heads" class="heads-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class=" item-selected heads item item-container"></li>
				<li data-itemnumber="1" class=" heads item item-container"></li>
				<li data-itemnumber="2" class=" heads item item-container"></li>
				<li data-itemnumber="3" class=" heads item item-container"></li>
			</ul>
		</div> 

		<div data-category="hairs" class="hairs-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class="item-selected hairs item item-container"></li>
				<li data-itemnumber="1" class="hairs item item-container"></li>
				<li data-itemnumber="2" class="hairs item item-container"></li>
				<li data-itemnumber="3" class="hairs item item-container"></li>
				<li data-itemnumber="4" class="hairs item item-container"></li>
				<li data-itemnumber="5" class="hairs item item-container"></li>
				<li data-itemnumber="6" class="hairs item item-container"></li>
				<li data-itemnumber="7" class="hairs item item-container"></li>
				<li data-itemnumber="8" class="hairs item item-container"></li>
				<li data-itemnumber="9" class="hairs item item-container"></li>
				<li data-itemnumber="10" class="hairs item item-container"></li>
				<li data-itemnumber="11" class="hairs item item-container"></li>
				<li data-itemnumber="12" class="hairs item item-container"></li>
				<li data-itemnumber="13" class="hairs item item-container"></li>
				<li data-itemnumber="14" class="hairs item item-container"></li>

			</ul>
		</div>

		<div data-category="eyes" class="eyes-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class="item-selected eyes item item-container"></li>
				<li data-itemnumber="1" class="eyes item item-container"></li>
				<li data-itemnumber="2" class="eyes item item-container"></li>
				<li data-itemnumber="3" class="eyes item item-container"></li>
				<li data-itemnumber="4" class="eyes item item-container"></li>
				<li data-itemnumber="5" class="eyes item item-container"></li>
				<li data-itemnumber="6" class="eyes item item-container"></li>
				<li data-itemnumber="7" class="eyes item item-container"></li>
				<li data-itemnumber="8" class="eyes item item-container"></li>
				<li data-itemnumber="9" class="eyes item item-container"></li>
				<li data-itemnumber="10" class="eyes item item-container"></li>
				<li data-itemnumber="11" class="eyes item item-container"></li>
			</ul>
		</div>

		<div data-category="eyebrows" class="eyebrows-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class="item-selected eyebrows item item-container"></li>
				<li data-itemnumber="1" class="eyebrows item item-container"></li>
				<li data-itemnumber="2" class="eyebrows item item-container"></li>
				<li data-itemnumber="3" class="eyebrows item item-container"></li>
				<li data-itemnumber="4" class="eyebrows item item-container"></li>
				<li data-itemnumber="5" class="eyebrows item item-container"></li>
				<li data-itemnumber="6" class="eyebrows item item-container"></li>
				<li data-itemnumber="7" class="eyebrows item item-container"></li>
			</ul>
		</div>

		<div data-category="noses" class="noses-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class="item-selected noses item item-container"></li>
				<li data-itemnumber="1" class="noses item item-container"></li>
				<li data-itemnumber="2" class="noses item item-container"></li>
				<li data-itemnumber="3" class="noses item item-container"></li>
				<li data-itemnumber="4" class="noses item item-container"></li>
				<li data-itemnumber="5" class="noses item item-container"></li>
				<li data-itemnumber="6" class="noses item item-container"></li>
			</ul>
		</div>

		<div data-category="mouths" class="mouths-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class="item-selected mouths item item-container"></li>
				<li data-itemnumber="1" class="mouths item item-container"></li>
				<li data-itemnumber="2" class="mouths item item-container"></li>
				<li data-itemnumber="3" class="mouths item item-container"></li>
				<li data-itemnumber="4" class="mouths item item-container"></li>
				<li data-itemnumber="5" class="mouths item item-container"></li>
				<li data-itemnumber="6" class="mouths item item-container"></li>
				<li data-itemnumber="7" class="mouths item item-container"></li>
			</ul>
		</div> 

		<div data-category="spectacles" class="spectacles-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class="spectacles item item-container"></li>
				<li data-itemnumber="1" class="spectacles item item-container"></li>
				<li data-itemnumber="2" class="spectacles item item-container"></li>
				<li data-itemnumber="3" class="spectacles item item-container"></li>
				<li data-itemnumber="4" class="spectacles item item-container"></li>
				<li data-itemnumber="5" class="spectacles item item-container"></li>
				<li class="no-item item item-selected spectacles item-container"></li>
			</ul>
		</div>

		<div data-category="facehairs" class="facehairs-section section" id="item-view">
			<ul class="randomizable-item-list">
				<li data-itemnumber="0" class="facehairs item item-container"></li>
				<li data-itemnumber="1" class="facehairs item item-container"></li>
				<li data-itemnumber="2" class="facehairs item item-container"></li>
				<li data-itemnumber="3" class="facehairs item item-container"></li>
				<li data-itemnumber="4" class="facehairs item item-container"></li>
				<li data-itemnumber="5" class="facehairs item item-container"></li>
				<li class="no-item item item-selected facehairs item-container"></li>
		</div> 

	</div>
</body>
<script type="text/javascript">
// hide broken (missing) images. (if an avatar has no glasses, beard, or hair-backing)
	document.addEventListener("DOMContentLoaded", function(event) {
	Array.from(document.querySelectorAll('img')).forEach(function(img){
  		img.onerror = function(){this.style.display='none';};
   })
});
</script>
<%= javascript_include_tag('test.js') %>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'comments' %>

<div class="section" id="avatar-view">
	<div class="avatar">
		<img id="body" src="/images/ears0.png">
		<img class="clothing" id="worn-skin" src="/<%= @post.skin %>"></img>
		<img class="clothing" id="worn-head" src="/<%= @post.head %>"></img>
		<img class="clothing" id="worn-top" src="/<%= @post.top %>"></img>
		<img class="clothing" id="worn-bottom" src="/<%= @post.bottom %>"></img>
		<img class="clothing" id="worn-hair" src="/<%= @post.hair %>"></img>
		<img class="clothing" id="hair-backing" src="/<%= @post.hairbacking %>"></img>
		<img class="clothing" id="worn-shoe" src="/<%= @post.shoe %>"></img>
		<img class="clothing" id="worn-eye" src="/<%= @post.eye %>"></img>
		<img class="clothing" id="worn-eyebrow" src="/<%= @post.eyebrow %>"></img>
		<img class="clothing" id="worn-spectacle" src="/<%= @post.spectacles %>"></img>
		<img class="clothing" id="worn-nose" src="/<%= @post.nose %>"></img>
		<img class="clothing" id="worn-mouth" src="/<%= @post.mouth %>"></img>
		<img class="clothing" id="worn-facehair" src="/<%= @post.facehair %>"></img>
	</div>
</div>